#  https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

installCRDs: true

securityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

prometheus:
  servicemonitor:
    enabled: true